# Generated by Django 5.0.4 on 2024-04-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
